# Bash mirror of scripts/panel-demo.ps1 — for macOS / Linux.
# Usage:
#   ./scripts/panel-demo.sh             # full panel run
#   SKIP_TESTS=1 ./scripts/panel-demo.sh
#   SKIP_BUILD=1 ./scripts/panel-demo.sh
#   STOP_AFTER=1 ./scripts/panel-demo.sh

set -euo pipefail

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
cd "$repo_root"

GREEN='\033[0;32m'; RED='\033[0;31m'; CYAN='\033[0;36m'; YELLOW='\033[0;33m'; NC='\033[0m'
step_idx=0
step() {
    step_idx=$((step_idx+1))
    local title="$1"; shift
    echo
    printf "${CYAN}=== [%d] %s ===${NC}\n" "$step_idx" "$title"
    local start=$SECONDS
    if "$@"; then
        printf "${GREEN}PASS  (%ds) — %s${NC}\n" "$((SECONDS-start))" "$title"
    else
        printf "${RED}FAIL  (%ds) — %s${NC}\n" "$((SECONDS-start))" "$title"
        exit 1
    fi
}

require_tool() { command -v "$1" >/dev/null || { echo "$2 not found on PATH"; exit 1; }; }

step "Pre-flight: required tools" bash -c '
    set -e
    for t in dotnet docker npm git curl; do command -v "$t" >/dev/null || { echo "missing: $t"; exit 1; }; done
    docker info >/dev/null
'

step "Repository identity" bash -c '
    git rev-parse --abbrev-ref HEAD
    git describe --tags --abbrev=0 2>/dev/null || true
    git log --oneline -n 10
'

step "dotnet build -c Release"      dotnet build TaskFlow.sln -c Release --nologo -v minimal

if [[ "${SKIP_TESTS:-0}" != "1" ]]; then
    step "dotnet test (43 tests)"   dotnet test TaskFlow.sln -c Release --no-build --nologo -v minimal
else
    printf "${YELLOW}(skipping tests by request)${NC}\n"
fi

step "dotnet format --verify-no-changes" dotnet format TaskFlow.sln --verify-no-changes -v minimal

step "SPA strict TS + Vite production build" bash -c '
    cd src/TaskFlow.Web
    [ -d node_modules ] || npm ci
    npm run build
'

if [[ "${SKIP_BUILD:-0}" == "1" ]]; then
    step "docker compose up -d" docker compose up -d
else
    step "docker compose up -d --build" docker compose up -d --build
fi

step "Wait for API + Web" bash -c '
    deadline=$((SECONDS+60))
    api=0; web=0
    while [ $SECONDS -lt $deadline ] && [ $api -eq 0 -o $web -eq 0 ]; do
        [ $api -eq 0 ] && curl -fsS http://localhost:5092/swagger/v1/swagger.json >/dev/null 2>&1 && api=1
        [ $web -eq 0 ] && curl -fsS http://localhost:8080/                       >/dev/null 2>&1 && web=1
        sleep 1
    done
    [ $api -eq 1 ] || { echo "API not ready"; exit 1; }
    [ $web -eq 1 ] || { echo "Web not ready"; exit 1; }
'

API="http://localhost:5092/api/v1"
EMAIL="panel+$(date +%Y%m%d%H%M%S)@taskflow.dev"
PASS="Panel-Demo-1!"

step "POST /auth/register (ephemeral panel user)" bash -c "
    TOKEN=\$(curl -fsS -X POST $API/auth/register -H 'content-type: application/json' \
        -d '{\"email\":\"$EMAIL\",\"password\":\"$PASS\"}' | sed -n 's/.*\"accessToken\":\"\\([^\"]*\\)\".*/\\1/p')
    [ -n \"\$TOKEN\" ] || { echo 'no token'; exit 1; }
    echo \$TOKEN > .panel.token
"
TOKEN="$(cat .panel.token)"; rm -f .panel.token

step "POST /tasks (create)" bash -c "
    TASK_ID=\$(curl -fsS -X POST $API/tasks \
        -H 'authorization: Bearer $TOKEN' -H 'content-type: application/json' \
        -d '{\"title\":\"Prepare panel walkthrough\",\"description\":\"Generated by panel-demo.sh\",\"dueDateUtc\":\"$(date -u -d '+7 days' +%Y-%m-%dT%H:%M:%SZ 2>/dev/null || date -u -v+7d +%Y-%m-%dT%H:%M:%SZ)\"}' \
        | sed -n 's/.*\"id\":\"\\([^\"]*\\)\".*/\\1/p')
    [ -n \"\$TASK_ID\" ] || { echo 'no task id'; exit 1; }
    echo \$TASK_ID > .panel.task
"
TASK_ID="$(cat .panel.task)"; rm -f .panel.task

step "GET /tasks (must include new id)" bash -c "
    curl -fsS $API/tasks -H 'authorization: Bearer $TOKEN' | grep -q $TASK_ID
"

step "DELETE /tasks/{id}" bash -c "
    curl -fsS -X DELETE $API/tasks/$TASK_ID -H 'authorization: Bearer $TOKEN' >/dev/null
"

step "GET /tasks WITHOUT token must return 401" bash -c "
    code=\$(curl -s -o /dev/null -w '%{http_code}' $API/tasks)
    [ \"\$code\" = '401' ]
"

step "POST /auth/login with seeded demo user" bash -c "
    curl -fsS -X POST $API/auth/login -H 'content-type: application/json' \
        -d '{\"email\":\"demo@taskflow.dev\",\"password\":\"Demo123!\"}' | grep -q accessToken
"

echo
printf "${GREEN}================================================================${NC}\n"
printf "${GREEN} ALL GATES PASSED — TaskFlow is live for the panel demo.${NC}\n"
printf "${GREEN}================================================================${NC}\n"
echo "  SPA            http://localhost:8080"
echo "  Swagger        http://localhost:5092/swagger"
echo "  Razor MVC      http://localhost:5092/"
echo "  Demo user      demo@taskflow.dev / Demo123!"
echo
echo "  Tear down with:  ./scripts/panel-demo-down.sh   (-p to also drop the volume)"

if [[ "${STOP_AFTER:-0}" == "1" ]]; then
    echo "Stopping containers (STOP_AFTER=1)…"
    docker compose down
fi
